# Generated by Django 5.0.4 on 2025-06-08 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ трек кода')),
                ('track_code', models.CharField(max_length=100, unique=True, verbose_name='Трек код')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('user_added', 'Добавлено пользователем'), ('warehouse_cn', 'Принято на склад (Китай)'), ('shipped_cn', 'Отправлено со склада (Китай)'), ('delivered', 'Доставлено на ПВЗ')], max_length=20, verbose_name='Статус трек-кода')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='О посылке')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес посылки (кг)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя владельца')),
            ],
        ),
    ]
