# Generated by Django 4.2.7 on 2025-09-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Общий вес (кг)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма чека')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ трек кода')),
                ('track_code', models.CharField(max_length=100, unique=True, verbose_name='Трек код')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('user_added', 'Добавлено пользователем'), ('warehouse_cn', 'Принято на склад (Китай)'), ('shipped_cn', 'Отправлено со склада (Китай)'), ('delivered', 'Доставлено на ПВЗ')], max_length=20, verbose_name='Статус трек-кода')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='О посылке')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вес посылки (кг)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя владельца')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myprofile.receipt')),
                ('track_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myprofile.trackcode')),
            ],
        ),
    ]
