# Generated by Django 5.2.7 on 2025-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_customerdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная скидка'),
        ),
    ]
